### ISSUE TITLE
G-SAN training with a new dataset

### ISSUE THREAD

**Issue by masih4** [lifangda01/GSAN-Demo#1]
Great study!
Two questions:
1- Could you please provide a sample data loader code for using G-SAN to train a segmentation/classification model?  
2- I suppose first I need to train the G-SAN and then use the trained G-SAN model in the data loader for training a segmentation/classification model. Is that true? how I can train G-SAN with a new dataset?

**Comment by lifangda01** [comment]
1. Sure -- I'll provide it in an update soon.
2. You don't need to retrain G-SAN yourself if your task-specific model is for HnE. You just need to use the pretrained weights as provided in the demo.

**Comment by masih4** [comment]
Thank you for your quick reply. Actually, I want to train G-SAN from scratch with a new dataset, so if you could provide steps on how to train it, that would be great.

**Comment by lifangda01** [comment]
Of course! Providing the training code might take a bit of additional work but I can do that for sure.

**Comment by lifangda01** [comment]
Finally got around to clean up the training code. Please take a look at the new `training` branch in case it helps.
